### PR TITLE
Bump `interpolate-components` to 1.1.1 (for React 16 compat)

### PR DESCRIPTION
**Pull request by ockham**
Also bump version, Changelog

See https://github.com/Automattic/interpolate-components/pull/12.

To Test
------

### CODE REVIEW

**Comment by ockham** [comment]
Ready for review!

**Comment by samouri** [comment]
@ockham: do we need to do anything other than ensure unit tests pass?

**Comment by ockham** [comment]
I just (pre-)released this as `1.8.4-alpha.4` and updated https://github.com/Automattic/wp-calypso/pull/19658, so let's use that PR to test if it works fine with Calypso.

**Comment by samouri** [comment]
why is moment-tz pinned to  a specific dep? ideally `wp-calypso` could decide

**Comment by samouri** [comment]
i checked `update/i18n-calypso` in wp-calypso, cleared node_modules and reinstalled, and translations actually worked better than ever.

This branch makes clicking update settings work on the first try, whereas on `master` it takes a second refresh.

💯 🎉 .

**Pull request merged**
