### PR TITLE
package.json: Bump interpolate-components to 1.0.5

### PR DESCRIPTION
**Pull request by ockham**
For the Calypso React 15 upgrade, i.e. https://github.com/Automattic/wp-calypso/pull/5116#issuecomment-225642078

cc @blowery @Tug

### CODE REVIEW

**Comment by blowery** [comment]
needs `make shrinkwrap` run too i think

**Comment by blowery** [comment]
looks good, ship away!

**Comment by blowery** [comment]
I take that back. We should bump the react dev here to 15 too

**Comment by ockham** [comment]
> I take that back. We should bump the react dep here to 15 too

a03b2b5

**Comment by Tug** [comment]
LGTM 👍 
Creating version `1.2.0` for this change!

**Pull request merged**
