### PR TITLE
Remove moment and moment-timezone from i18n-calypso

### PR DESCRIPTION
**Pull request by blowery**
Clients will now need to require them themselves to use them. This frees up clients of i18n-calypso to load moments translations and timezone data any way they see fit, or to not use moment at all.

### CODE REVIEW

**Comment by sirreal** [comment]
- 👍 for `v3` (alpha)
- Does bundling `moment` provide any value beyond just providing the module?
- How do you see this moving forward? Should we open a `v3` branch that can receive merges from master to maintain them in parallel? next dist-tag on npm?

**Comment by ockham** [comment]
I haven't released v2 yet (nor have I merged #64), so we can still include this change in it.

**Comment by blowery** [comment]
> Does bundling moment provide any value beyond just providing the module?

I think bundling `moment` actively hurts clients of i18n-calypso. So, no. :) I wouldn't recommend anyone depend on it.

**Comment by blowery** [comment]
> I haven't released v2 yet (nor have I merged #64), so we can still include this change in it.

I'd be ok with that.

**Comment by hewsut** [comment]
Make y'all a deal -- merge this, I'll Flow type the package and submit a libdef to https://github.com/flow-typed/flow-typed.

**Comment by sirreal** [comment]
Is there really anything left to do here other than rebase and put this on a v3 branch so v2 can continue to be maintained in parallel? This seems fine for an alpha.

Then we could see about releasing that to npm, optionally with a `next` dist-tag (being carefuly not to `latest` tag it).

@hewsut Care to tackle any of that? 😁

**Comment by blowery** [comment]
Closing until we get this moved into the calypso repo

**Pull request closed without merging**
